export const data = {
    "version": 2,
    "name": "empty",
    "width": 20,
    "height": 20,
    "tilewidth": 64,
    "tileheight": 64,
    "orientation": "orthogonal",
    "renderorder": "right-down",
    "properties": {},
    "tilesets": [
        {
            "endgid": 4,
            "firstgid": 1,
            "image": "063e02484c3349ffb06df4de4e0f08ca_1698229313.png",
            "imageURL": "https://dev-oss.vland.live/back/public/resource/063e02484c3349ffb06df4de4e0f08ca_1698229313.png",
            "imageheight": 64,
            "imagewidth": 256,
            "name": "packedTileset-0",
            "tileID": "2f0da16c-9d0e-4965-b218-cf95778328c3",
            "tileNums": 4,
            "tileheight": 64,
            "tilewidth": 64,
            "zIndex": null
        }
    ],
    "layers": [
        {
            "name": "ground",
            "type": "tilelayer",
            "tiles": [],
            "zIndex": 1,
            "data": {
                "0": 1
            },
            "height": 20,
            "width": 20,
            "visible": true,
            "opacity": 1,
            "x": 0,
            "y": 0
        },
        {
            "name": "wallBehind",
            "type": "tilelayer",
            "tiles": [],
            "zIndex": 2,
            "data": {
                "0": 1
            },
            "height": 20,
            "width": 20,
            "visible": true,
            "opacity": 1,
            "x": 0,
            "y": 0
        },
        {
            "name": "freeObjBelowAvatar",
            "type": "tilelayer",
            "tiles": [],
            "zIndex": 3,
            "data": {
                "0": 1
            },
            "height": 20,
            "width": 20,
            "visible": true,
            "opacity": 1,
            "x": 0,
            "y": 0
        },
        {
            "name": "objBelowAvatar",
            "type": "tilelayer",
            "tiles": [],
            "zIndex": 4,
            "data": {
                "0": 1
            },
            "height": 20,
            "width": 20,
            "visible": true,
            "opacity": 1,
            "x": 0,
            "y": 0
        },
        {
            "name": "avatar",
            "type": "tilelayer",
            "tiles": [],
            "zIndex": 5,
            "data": {
                "0": 1,
                "1": 1,
                "2": 1,
                "3": 1,
                "4": 1,
                "5": 1,
                "6": 1,
                "7": 1,
                "8": 1,
                "9": 1,
                "10": 1,
                "11": 1,
                "12": 1,
                "13": 1,
                "14": 1,
                "15": 1,
                "16": 1,
                "17": 1,
                "18": 1,
                "19": 1,
                "20": 1,
                "39": 1,
                "40": 1,
                "59": 1,
                "60": 1,
                "79": 1,
                "80": 1,
                "99": 1,
                "100": 1,
                "119": 1,
                "120": 1,
                "139": 1,
                "140": 1,
                "159": 1,
                "160": 1,
                "179": 1,
                "180": 1,
                "199": 1,
                "200": 1,
                "219": 1,
                "220": 1,
                "239": 1,
                "240": 1,
                "259": 1,
                "260": 1,
                "279": 1,
                "280": 1,
                "299": 1,
                "300": 1,
                "319": 1,
                "320": 1,
                "339": 1,
                "340": 1,
                "359": 1,
                "360": 1,
                "379": 1,
                "380": 1,
                "381": 1,
                "382": 1,
                "383": 1,
                "384": 1,
                "385": 1,
                "386": 1,
                "387": 1,
                "388": 1,
                "389": 1,
                "390": 1,
                "391": 1,
                "392": 1,
                "393": 1,
                "394": 1,
                "395": 1,
                "396": 1,
                "397": 1,
                "398": 1,
                "399": 1
            },
            "height": 20,
            "width": 20,
            "visible": true,
            "opacity": 1,
            "x": 0,
            "y": 0
        },
        {
            "name": "objAboveAvatar",
            "type": "tilelayer",
            "tiles": [],
            "zIndex": 6,
            "data": {
                "0": 1
            },
            "height": 20,
            "width": 20,
            "visible": true,
            "opacity": 1,
            "x": 0,
            "y": 0
        },
        {
            "name": "wallFront",
            "type": "tilelayer",
            "tiles": [],
            "zIndex": 7,
            "data": {
                "0": 1
            },
            "height": 20,
            "width": 20,
            "visible": true,
            "opacity": 1,
            "x": 0,
            "y": 0
        },
        {
            "name": "freeObjAboveAvatar",
            "type": "tilelayer",
            "tiles": [],
            "zIndex": 8,
            "data": {
                "0": 1
            },
            "height": 20,
            "width": 20,
            "visible": true,
            "opacity": 1,
            "x": 0,
            "y": 0
        },
        {
            "name": "flagObj",
            "type": "tilelayer",
            "tiles": [],
            "zIndex": 9,
            "data": {
                "0": 1,
                "210": 1
            },
            "height": 20,
            "width": 20,
            "visible": true,
            "opacity": 1,
            "x": 0,
            "y": 0
        }
    ],
    "objAboveAvatarPos": [],
    "objBelowAvatarPos": [
        {
            "id": "04f8fdd9-358d-438a-b747-f5b49e453094",
            "zIndex": 3,
            "left": 5,
            "top": 5,
            "width": 1,
            "height": 1,
            "imageURL": "https://dev-oss.vland.live/back/public/resource/d9a5acbffe89404585658b97bfda9647_1698229314.png",
            "imageX": 130,
            "imageY": 0
        },
        {
            "id": "b6726391-b434-4d0e-8e3c-1b41209361af",
            "zIndex": 3,
            "left": 7,
            "top": 6,
            "width": 2,
            "height": 2,
            "imageURL": "https://dev-oss.vland.live/back/public/resource/d9a5acbffe89404585658b97bfda9647_1698229314.png",
            "imageX": 0,
            "imageY": 0
        }
    ],
    "removableObstacles": [],
    "birthPos": [
        {
            "x": 10,
            "y": 10
        }
    ],
    "interactivePos": [],
    "freeObjAboveAvatarPos": [
        {
            "id": "b2787526-81a2-4735-b830-fe935e12f5f7",
            "type": "image",
            "imageURL": "https://dev-oss.vland.live/back/public/resource/e6715f62c09c49308a2481a008b5b944_1673510526.bin",
            "imageWidth": 307,
            "imageHeight": 307,
            "scaleX": 1,
            "scaleY": 1,
            "imageLeft": 843.4230769230769,
            "imageTop": 571.1153846153846,
            "zIndex": 7,
            "angle": 0,
            "opacity": 1
        },
        {
            "id": "67f51bf5-c8b3-43a3-bd45-5e13214e0210",
            "type": "text",
            "scaleX": 1,
            "scaleY": 1,
            "textColor": "#000",
            "textContent": "qqq",
            "textHeight": 27.119999999999997,
            "textLeft": 421.53846153846155,
            "textSize": 24,
            "textTop": 514.4184615384617,
            "textWidth": 100,
            "zIndex": 7,
            "opacity": 1,
            "isItalic": false,
            "isBold": false,
            "isUnderline": false,
            "horizontalAlign": "LEFT",
            "lineHeight": 28.799999999999997,
            "angle": 0
        }
    ],
    "freeObjBelowAvatarPos": [],
    "background": null,
    "skybox": null,
    "privateAreas": [],
    "broadcasts": [],
    "objects": [
        {
            "__typename": "tilemap",
            "id": "04f8fdd9-358d-438a-b747-f5b49e453094",
            "zIndex": 4,
            "left": 320,
            "top": 320,
            "width": 64,
            "height": 64,
            "image": "9836685c09a945829f57514ba237ff2e_1649327359.png",
            "imageURL": "https://dev-oss.vland.live/material/system/9836685c09a945829f57514ba237ff2e_1649327359.png",
            "tileID": "reFNrWJep-FdtG1x4DrJq",
            "userLayer": 2,
            "isCollider": true,
            "isMaskPlayer": false,
            "effect3D": false,
            "isbirth": false,
            "isPrivateArea": false,
            "isBillboard": false,
            "describe": "",
            "imageheight": 64,
            "imagewidth": 64,
            "name": "小木凳",
            "tileLeft": null,
            "tileNums": 1,
            "tileTop": null,
            "tileheight": 64,
            "tilewidth": 64,
            "triggerEnabled": false,
            "trigger": {
                "type": 0
            },
            "triggerEvent": "click",
            "triggerName": "",
            "triggerAction": {
                "type": "none"
            },
            "triggerGlobal": false,
            "limitTriggerTimes": false,
            "maxTriggerTimes": null,
            "triggerDistance": null,
            "interactiveType": 0,
            "interactiveURL": "",
            "interactiveData": null,
            "interactiveDistance": 1,
            "urlOpenType": 0,
            "accessUsernameAndUID": false,
            "accessUserToken": false,
            "accessUserEmail": false,
            "interactiveMsg": null,
            "promptTextFontSize": 15,
            "promptIconHidden": false,
            "promptIconUrl": null,
            "promptIconResource": null,
            "dialogBgcolor": "rgba(49, 34, 92, 0.9)",
            "dialogAlignment": null,
            "spin": {
                "status": true,
                "images": [
                    {
                        "name": "小木凳",
                        "url": "https://dev-oss.vland.live/material/system/9836685c09a945829f57514ba237ff2e_1649327359.png",
                        "h": 64,
                        "w": 64
                    },
                    {
                        "name": "MA餐椅_2.png",
                        "url": "https://dev-oss.vland.live/material/system/624ebcff4ff28daf5e79bafe/6f7cab7711664461b8b7f14ef3babbab_1649327359.png",
                        "h": 64,
                        "w": 64
                    },
                    {
                        "name": "MA餐椅_3.png",
                        "url": "https://dev-oss.vland.live/material/system/624ebcff4ff28daf5e79bafe/2352f65faa1e48dfa3b88044feae6259_1649327359.png",
                        "h": 64,
                        "w": 64
                    },
                    {
                        "name": "MA餐椅_4.png",
                        "url": "https://dev-oss.vland.live/material/system/624ebcff4ff28daf5e79bafe/809f688b4f2b4773b169f21647c4e6f5_1649327359.png",
                        "h": 64,
                        "w": 64
                    }
                ]
            },
            "resource": null,
            "anchorName": "",
            "showOnMap": true,
            "broadcastScreenType": 0,
            "showFocusButton": false
        },
        {
            "__typename": "tilemap",
            "id": "b6726391-b434-4d0e-8e3c-1b41209361af",
            "zIndex": 4,
            "left": 448,
            "top": 384,
            "width": 128,
            "height": 128,
            "image": "d2369f784bd548fbb83541a29672f0af_1649327359.png",
            "imageURL": "https://dev-oss.vland.live/material/system/d2369f784bd548fbb83541a29672f0af_1649327359.png",
            "tileID": "bjIVJz-42r80QvEXICZV-",
            "userLayer": 2,
            "isCollider": false,
            "isMaskPlayer": false,
            "effect3D": false,
            "isbirth": false,
            "isPrivateArea": false,
            "isBillboard": false,
            "describe": "",
            "imageheight": 128,
            "imagewidth": 128,
            "name": "双人沙发1",
            "tileLeft": null,
            "tileNums": 4,
            "tileTop": null,
            "tileheight": 64,
            "tilewidth": 64,
            "triggerEnabled": false,
            "trigger": {
                "type": 0
            },
            "triggerEvent": "click",
            "triggerName": "",
            "triggerAction": {
                "type": "none"
            },
            "triggerGlobal": false,
            "limitTriggerTimes": false,
            "maxTriggerTimes": null,
            "triggerDistance": null,
            "interactiveType": 0,
            "interactiveURL": "",
            "interactiveData": null,
            "interactiveDistance": 1,
            "urlOpenType": 0,
            "accessUsernameAndUID": false,
            "accessUserToken": false,
            "accessUserEmail": false,
            "interactiveMsg": null,
            "promptTextFontSize": 15,
            "promptIconHidden": false,
            "promptIconUrl": null,
            "promptIconResource": null,
            "dialogBgcolor": "rgba(49, 34, 92, 0.9)",
            "dialogAlignment": null,
            "spin": {
                "status": true,
                "images": [
                    {
                        "name": "双人沙发1",
                        "url": "https://dev-oss.vland.live/material/system/d2369f784bd548fbb83541a29672f0af_1649327359.png",
                        "h": 128,
                        "w": 128
                    },
                    {
                        "name": "MA双红沙发_2.png",
                        "url": "https://dev-oss.vland.live/material/system/624ebcff4ff28daf5e79bb2f/2c4159f29c0f4215bcaca59ed8605193_1649327359.png",
                        "h": 128,
                        "w": 64
                    },
                    {
                        "name": "MA双红沙发_3.png",
                        "url": "https://dev-oss.vland.live/material/system/624ebcff4ff28daf5e79bb2f/c48ba9dd82054ceba26f513798e3df5b_1649327359.png",
                        "h": 128,
                        "w": 128
                    },
                    {
                        "name": "MA双红沙发_4.png",
                        "url": "https://dev-oss.vland.live/material/system/624ebcff4ff28daf5e79bb2f/dd77935d35f241699a039db0c4ec1a5f_1649327359.png",
                        "h": 128,
                        "w": 64
                    }
                ]
            },
            "resource": null,
            "anchorName": "",
            "showOnMap": true,
            "broadcastScreenType": 0,
            "showFocusButton": false
        },
        {
            "__typename": "image",
            "id": "b2787526-81a2-4735-b830-fe935e12f5f7",
            "materialId": "Ok4T-XIRCOKbsVmq4TjKZ",
            "zIndex": 8,
            // "left": 843.4230769230769 + 120,
            // "top": 401.88461538461536,
            left: 10,
            top: 10,
            "width": 307,
            "height": 307,
            "imageURL": "https://dev-oss.vland.live/back/material/system/91ed1758bb5a480291a55afd332f8040_1660563253.gif",
            "imageWidth": 307,
            "imageHeight": 307,
            "name": "不理你",
            "userLayer": 5,
            "isMaskPlayer": true,
            "effect3D": false,
            "isBackgroundImage": false,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 0.47
        },
        {
            "__typename": "text",
            "id": "67f51bf5-c8b3-43a3-bd45-5e13214e0210",
            "zIndex": 8,
            "left": 421.53846153846155,
            "top": 738.4615384615383,
            "width": 100,
            "height": 27.119999999999997,
            "content": "qqq",
            "fontSize": 24,
            "color": "#000",
            "userLayer": 5,
            "isMaskPlayer": true,
            "opacity": 1,
            "isItalic": false,
            "isBold": false,
            "isUnderline": false,
            "horizontalAlign": "LEFT",
            "lineHeight": null,
            "angle": 0
        },
        {
            "__typename": "tilemap",
            "id": "b81087a3-3ab8-4184-aed8-e9132139129e",
            "zIndex": 9,
            "left": 640,
            "top": 640,
            "width": 64,
            "height": 64,
            "image": "8ca27ba837214fbdaac6dee1863bfca4_1649646614.png",
            "imageURL": "https://dev-oss.vland.live/material/system/8ca27ba837214fbdaac6dee1863bfca4_1649646614.png",
            "tileID": "g84EEr5lEQAQdFhHZ71Bb",
            "userLayer": 1,
            "isCollider": false,
            "isMaskPlayer": false,
            "effect3D": false,
            "isbirth": true,
            "isPrivateArea": false,
            "isBillboard": false,
            "describe": "",
            "imageheight": 64,
            "imagewidth": 64,
            "name": "出生点",
            "tileLeft": null,
            "tileNums": 1,
            "tileTop": null,
            "tileheight": 64,
            "tilewidth": 64,
            "triggerEnabled": false,
            "trigger": {
                "type": 0
            },
            "triggerEvent": "click",
            "triggerName": "",
            "triggerAction": {
                "type": "none"
            },
            "triggerGlobal": false,
            "limitTriggerTimes": false,
            "maxTriggerTimes": null,
            "triggerDistance": null,
            "interactiveType": 0,
            "interactiveURL": "",
            "interactiveData": null,
            "interactiveDistance": 1,
            "urlOpenType": 0,
            "accessUsernameAndUID": false,
            "accessUserToken": false,
            "accessUserEmail": false,
            "interactiveMsg": null,
            "promptTextFontSize": 15,
            "promptIconHidden": false,
            "promptIconUrl": null,
            "promptIconResource": null,
            "dialogBgcolor": "rgba(49, 34, 92, 0.9)",
            "dialogAlignment": null,
            "spin": {
                "status": false,
                "images": []
            },
            "resource": null,
            "anchorName": "",
            "showOnMap": true,
            "broadcastScreenType": 0,
            "showFocusButton": false
        }
    ],
    "backgroundImage": null,
    "backgroundSticker": {
        "id": "53e3bd4d-ebb9-48f5-b8c6-f624d7f7c634",
        "name": "306590525_615010047015322_363830067717474452_n.jpeg",
        "url": "https://dev-oss.vland.live/back/member/repository/133/4f505f40014f400aa22e36fb587a9f2e_1674992283.jpeg",
        "type": 2,
        "typeChild": 2
    },
    "skyboxStickers": {
        "left": null,
        "right": null,
        "top": null,
        "bottom": null,
        "front": null,
        "back": null
    },
    "personalStickers": [],
    "effect3DObjectIds": [],
    "view3DAreaPos": [],
    "specialInteractionAreaPos": [],
    "npcs": [],
    "npcScriptUrl": null,
    "npcCorpusUrl": null,
    "portals": [],
    "anchors": [],
    "view3DAreaFocusPoints": []
}